ARG ROOT_VERSION=6.30.02-alma9
FROM rootproject/root:${ROOT_VERSION} AS build

LABEL maintainer.name="Eventdisplay Team"
LABEL maintainer.email="gernot.maier@desy.de"

WORKDIR /eventdisplay_workdir/
ENV EVNDISP /eventdisplay_workdir/

# Install hessioxx
COPY hessioxxx.tar.gz .
RUN tar -xvzf hessioxxx.tar.gz && \
   cd hessioxxx && \
   make EXTRA_DEFINES="-DCTA_PROD4 -DMAXIMUM_TELESCOPES=180 -DWITH_GSL_RNG" && \
   cd .. && rm -f hessioxxx.tar.gz
ENV HESSIOSYS ${EVNDISP}/hessioxxx
ENV LD_LIBRARY_PATH "${HESSIOSYS}/lib:${LD_LIBRARY_PATH}"

# Install Eventdisplay
ENV EVNDISPSYS ${EVNDISP}/Eventdisplay/
ENV SOFASYS ${EVNDISPSYS}/sofa/
RUN mkdir -p ${EVNDISP}/Eventdisplay
COPY Eventdisplay ${EVNDISP}/
RUN cd ${EVNDISPSYS} && ./install_sofa.sh
RUN cd ${EVNDISPSYS} && \
    make -j 4 CTA GRIDPROD=CTAGRID CTAPROD=PROD5 && \
    rm -f obj/*.o obj/*.cpp

ENV LD_LIBRARY_PATH "${EVNDISPSYS}/obj:${EVNDISPSYS}/lib:${LD_LIBRARY_PATH}"
ENV ROOT_INCLUDE_PATH ${EVNDISPSYS}/inc

# Install Eventdisplay Analysis files
RUN git clone --depth 1 https://github.com/Eventdisplay/Eventdisplay_AnalysisFiles_CTA.git
ENV CTA_EVNDISP_AUX_DIR ${EVNDISP}/Eventdisplay_AnalysisFiles_CTA/
ENV OBS_EVNDISP_AUX_DIR ${EVNDISP}/Eventdisplay_AnalysisFiles_CTA
ENV OBS_USER_DATA_DIR /tmp/

# Copy run script
RUN cp ${EVNDISPSYS}/dockerfiles/Dockerfile-cta-prod5-run.sh ${EVNDISP}/run.sh
