---
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request
  # events but only for the main branch
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        root: [rootproject/root:latest, rootproject/root:6.24.02-ubuntu20.04]
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.root }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: build
        run: |
          root-config --version
          export EVNDISPSYS=$(echo $GITHUB_WORKSPACE)
          export SOFASYS=${EVNDISPSYS}/sofa
          echo "EVN $EVNDISPSYS"
          echo "GHE $GITHUB_WORKSPACE"
          ./install_sofa.sh CI
          echo "SOFA $SOFASYS"
          echo "GHA $GITHUB_WORKSPACE"
          #make -j 4 CTAnohessio
          make printRunParameter
