---
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request
  # events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: rootproject/root
    env:
      EVNDISPSYS: ${{ env.GITHUB_WORKSPACE }}
      SOFASYS: ${{ env.GITHUB_WORKSPACE }}/sofa

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: build
        run: |
          root-config --version
          echo "GHE $GITHUB_WORKSPACE"
          pwd
          ./install_sofa.sh CI
          ls
          echo "SOFA $SOFASYS"
          echo "GHA $GITHUB_WORKSPACE"
          ls -l $SOFASYS/include/
          make -j 4 VTS
