# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
name: CTA-Prod5 Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-cta-prod5-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: 'Eventdisplay'

      - name: Set build arguments
        run: |
          if [[ "${{ github.event_name }}" == 'pull_request' ]]; then
            echo "BUILD_BRANCH=${GITHUB_HEAD_REF}" >> "$GITHUB_ENV"
          else
            echo "BUILD_BRANCH=${GITHUB_REF#refs/heads/}" >> "$GITHUB_ENV"
          fi

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=ref,event=pr,suffix=-cta-prod5
            type=semver,pattern={{major}}.{{minor}}.{{patch}},suffix=-cta-prod5
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: hessioxx
        run: |
          wget --no-verbose https://syncandshare.desy.de/index.php/s/${{ secrets.CLOUD_HESSIOXX_20230731 }}/download
          mv download hessioxxx.tar.gz

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: BUILD_BRANCH=${{ env.BUILD_BRANCH }}
          push: ${{ github.event_name != 'pull_request' }}
          file: ./Eventdisplay/dockerfiles/Dockerfile-cta-prod5
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
