# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
name: CTA-slib Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build-cta-slib-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          path: 'Eventdisplay'

      - name: Set build arguments
        run: |
          if [[ "${{ github.event_name }}" == 'pull_request' ]]; then
            echo "BUILD_BRANCH=${GITHUB_HEAD_REF}" >> "$GITHUB_ENV"
          else
            echo "BUILD_BRANCH=${GITHUB_REF#refs/heads/}" >> "$GITHUB_ENV"
          fi
          echo "BUILD BRANCH ${{ env.BUILD_BRANCH }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=ref,event=pr,suffix=-cta-slib
            type=semver,pattern={{major}}.{{minor}}.{{patch}},suffix=-cta-slib
            type=schedule,pattern={{date 'YYYYMMDD'}},suffix=-cta-slib
            type=raw,value={{date 'YYYYMMDD-HHmmss'}},suffix=-cta-slib
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: latest=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: BUILD_BRANCH=${{ env.BUILD_BRANCH }}
          push: ${{ github.event_name != 'pull_request' }}
          file: ./Eventdisplay/dockerfiles/Dockerfile-cta-slib
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}-cta-slib
